Fixed content view size to be correct
scenee/FloatingPanel pull request #444
Opened 2021-03-03 07:52 UTC by itsol-ka

Content view size is incorrect when using autolayout for content view.
Fixed content view size to be correct.

maybe related #259

2021-03-04 09:19 UTC, scenee requested changes

2021-03-04 09:19 UTC, scenee commented on Tests/SurfaceViewTests.swift
> +        contentView.translatesAutoresizingMaskIntoConstraints = false
This line should be `titleLabel.translatesAutoresizingMaskIntoConstraints = false`. And if it changes, then this test case is passed even if the priority is still `.required - 1`. So this test case is not a sufficient reason for the priority change.

The background where the priority was set to `.required - 1(= 999)` is https://github.com/scenee/FloatingPanel/pull/359.  So we have to take care of its case.

2021-03-05 04:57 UTC, itsol-ka commented on Tests/SurfaceViewTests.swift
> +        contentView.translatesAutoresizingMaskIntoConstraints = false
Thank you for pointing out the test mistake.
I will rethink

2021-04-28 19:18 UTC, Batvos commented
Hi,

This PR fixed my issue with content size when I use uicollectionview with animated snapshot inside content view.
@scenee Could merge it or clarify what should be done to accept this PR.

2021-04-29 02:41 UTC, scenee commented
@Batvos Is the content mode(`FloatingPanelController.contentMode`) `static`? I think we need these priority change according the content mode.

2021-11-27 00:47 UTC, scenee commented
Hi there,
I've finally acknowledged this priority issue to be resolved for the `.static` content mode in #515. So I've create #519.
I closed this PR but I really appreciate your PR to let me know this issue for the first time.

2021-11-27 00:47 UTC, closed without merging

2021-11-30 08:40 UTC, itsol-ka commented
Thank you for fixing the bug.